# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altitude_logger.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'altitude_logger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61ltitude_logger.proto\x12\x0e\x61ltitudelogger\"V\n\x12\x41ltitudeLogRequest\x12\x12\n\naccess_key\x18\x01 \x01(\t\x12\x16\n\x0estart_datetime\x18\x02 \x01(\t\x12\x14\n\x0c\x65nd_datetime\x18\x03 \x01(\t\"\x88\x01\n\x0c\x41ltitudeData\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\t\x12\x10\n\x08\x61ltitude\x18\x02 \x01(\x02\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x10\n\x08pressure\x18\x04 \x01(\x02\x12\x1a\n\x12sea_level_pressure\x18\x05 \x01(\x02\x12\x11\n\televation\x18\x06 \x01(\x02\"A\n\x13\x41ltitudeLogResponse\x12*\n\x04logs\x18\x01 \x03(\x0b\x32\x1c.altitudelogger.AltitudeData2k\n\x0e\x41ltitudeLogger\x12Y\n\x0eGetAltitudeLog\x12\".altitudelogger.AltitudeLogRequest\x1a#.altitudelogger.AltitudeLogResponseB*\n\x0e\x61ltitudeloggerB\x18\x41ltitudeLoggerOuterClassb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altitude_logger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016altitudeloggerB\030AltitudeLoggerOuterClass'
  _globals['_ALTITUDELOGREQUEST']._serialized_start=41
  _globals['_ALTITUDELOGREQUEST']._serialized_end=127
  _globals['_ALTITUDEDATA']._serialized_start=130
  _globals['_ALTITUDEDATA']._serialized_end=266
  _globals['_ALTITUDELOGRESPONSE']._serialized_start=268
  _globals['_ALTITUDELOGRESPONSE']._serialized_end=333
  _globals['_ALTITUDELOGGER']._serialized_start=335
  _globals['_ALTITUDELOGGER']._serialized_end=442
# @@protoc_insertion_point(module_scope)
